name: Provenance

on:
  pull_request:
    branches:
      - main
    types:
      - closed
permissions:
  contents: read
jobs:
  check-provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Merge Main into Contributors
        uses: devvspaces/merge-branches@v1
        if: ${{ github.event.pull_request.merged }}
        with:
          token: ${{ secrets.NUXT_GITHUB_TOKEN }}
          from_branch: main
          to_branch: contributors
